################################################################
## Packages / Heishamon
################################################################

################################################################
## Changelog
################################################################
##
## 1.0.0 (08-01-2020)
##   Added
##   - Initial version
##
## 1.1.0 (10-01-2020)
##   Added
##   - Added power switch and Fan RPM sensors
##
## 1.2.0 (17-05-2020)
##   Fixed
##   - New/changed topics
##
## 2.0.0 (20-01-2021)
##   Added
##   - Adjusted to GoHeishaMon
##   - HA Discovery enabled sensors removed
##
## 2.1.0 (27-01-2021)
##   - New selectors added
##   - MQTT command topic naming scheme change
##   - Debounce commands
##
## 2.2.0 (02-02-2021)
##   - Rework Heat/Cool Curve setting to input_number
##
## 2.3.0 (20-08-2021)
##   - Removing new autodiscovery entities - select, number
##

# sensor #
##########
sensor:
  #### SENSORS BELOW ARE NOT IN FIRMWARE ####
  #Power use/production
  - platform: template
    sensors:
      aquarea_power_production:
        friendly_name: "Aquarea Power Production"
        unit_of_measurement: "W"
        value_template: >-
          {% if states('sensor.dhw_power_production') != "0" %}
            {{ states('sensor.dhw_power_production') }}
          {% elif states('sensor.cool_power_production') != "0" %}
            {{ states('sensor.cool_power_production') }}
          {% else %}
            {{ states('sensor.heat_power_production') }}
          {% endif %}
      aquarea_power_consumption:
        friendly_name: "Aquarea Power Consumption"
        unit_of_measurement: "W"
        value_template: >-
          {% if states('sensor.dhw_power_consumption') != "0" %}
            {{ states('sensor.dhw_power_consumption') }}
          {% elif states('sensor.cool_power_consumption') != "0" %}
            {{ states('sensor.cool_power_consumption') }}
          {% else %}
            {{ states('sensor.heat_power_consumption') }}
          {% endif %}
  #COP Calculations
  - platform: template
    sensors:
      aquarea_cop:
        friendly_name: "Aquarea COP"
        unit_of_measurement: "x"
        value_template: >-
          {% if states('sensor.aquarea_power_production') != "Unknown" %}
            {% if states('sensor.aquarea_power_consumption') > "0" %}
              {{ '%0.1f' % ((states('sensor.aquarea_power_production') | float ) / (states('sensor.aquarea_power_consumption') | float)) }}
            {% else %}
              0.0
            {% endif %}
          {% else %}
            unavailable
          {% endif %}

# switch #
##########
switch:
  #Turn on/off holiday mode
  - platform: mqtt
    name: Set Holiday Mode
    availability_topic: "panasonic_heat_pump/LWT"
    command_topic: "panasonic_heat_pump/main/Holiday_Mode_State/set"
    state_topic: "panasonic_heat_pump/main/Holiday_Mode_State"
    qos: 0
    payload_on: "1"
    payload_off: "0"
    state_on: "On"
    state_off: "Off"
    value_template: >-
      {% if value == "Off" %}
        Off
      {% elif value == "Active" or value == "Scheduled" %}
        On
      {% endif %}
    retain: false
