################################################################
## Packages / Heishamon
################################################################

################################################################
## Changelog
################################################################
##
## 1.0.0 (08-01-2020)
##   Added
##   - Initial version
##
## 1.1.0 (10-01-2020)
##   Added
##   - Added power switch and Fan RPM sensors
##
## 1.2.0 (17-05-2020)
##   Fixed
##   - New/changed topics


# Automations #
###############
automation:
  #Fetches quiet level from status and sets the selector accordingly
  - alias: Set quiet level selector
    trigger:
      platform: mqtt
      topic: "panasonic_heat_pump/main/Quiet_Mode_Level"
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.heishamon_quietmode
        option: "{{ trigger.payload }}"
  #Sets quiet level to the selected value
  - alias: Set quiet level
    trigger:
      platform: state
      entity_id: input_select.aquarea_quiet_mode
    action:
      service: mqtt.publish
      data_template:
        topic: panasonic_heat_pump/commands/SetQuietMode
        retain: false #IMPORTANT! ALWAYS set retain flag false for commands!
        payload_template: "{{ states('input_select.heishamon_quietmode') }}"
  
  #Fetches powerful level from status and sets the selector accordingly
  - alias: Set powerful level selector
    trigger:
      platform: mqtt
      topic: "panasonic_heat_pump/main/Powerful_Mode_Time"
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.aquarea_powerful_mode
        option: "{{ trigger.payload }}"
  #Sets powerful level to the selected value
  - alias: Set powerful level
    trigger:
      platform: state
      entity_id: input_select.aquarea_powerful_mode
    action:
      service: mqtt.publish
      data_template:
        topic: panasonic_heat_pump/commands/SetPowerfulMode
        retain: false #IMPORTANT! ALWAYS set retain flag false for commands!
        payload_template: "{{ states('input_select.aquarea_powerful_mode') }}"
  
  #Fetches operating mode from status and sets the selector accordingly
  - alias: Set operating mode selector
    trigger:
      platform: mqtt
      topic: "panasonic_heat_pump/main/Operating_Mode_State"
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.aquarea_operating_mode
        option: "{{ trigger.payload }}"
  #Sets heatmode to the selected value
  - alias: Set operating mode
    trigger:
      platform: state
      entity_id: input_select.aquarea_operating_mode
    action:
      service: mqtt.publish
      data_template:
        topic: panasonic_heat_pump/commands/SetOperationMode
        retain: false #IMPORTANT! ALWAYS set retain flag false for commands!
        payload_template: "{{ states('input_select.aquarea_operating_mode') }}"
  
  - alias: Set zones state selector
    trigger:
      platform: mqtt
      topic: "panasonic_heat_pump/main/Zones_State"
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.aquarea_zones
        option: "{{ trigger.payload }}"
  - alias: Set zones state
    trigger:
      platform: state
      entity_id: input_select.aquarea_zones
    action:
      service: mqtt.publish
      data_template:
        topic: panasonic_heat_pump/commands/SetZones
        retain: false
        payload_template: "{{ states('input_select.aquarea_zones') }}"
  
  #Fetches heatshift temperature from status and sets the selector accordingly
  - alias: Set heat offset selector
    trigger:
      platform: mqtt
      topic: "panasonic_heat_pump/main/Z1_Heat_Request_Temp"
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.aquarea_heat_offset
        value: >-
          {{ "%.1f" % (trigger.payload | int) }}
  #Sets heatshift temperature to the selected value
  - alias: Set heat offset
    trigger:
      platform: state
      entity_id: input_number.aquarea_heat_offset
    action:
      service: mqtt.publish
      data_template:
        topic: panasonic_heat_pump/commands/SetZ1HeatRequestTemperature
        retain: false #IMPORTANT! ALWAYS set retain flag false for commands!
        payload_template: >-
          {{ "%.0f" % (states('input_number.aquarea_heat_offset') | int) }}
  
  #Fetches tank target temperature from status and sets the selector accordingly
  - alias: Set tank target temperature selector
    trigger:
      platform: mqtt
      topic: "panasonic_heat_pump/main/DHW_Target_Temp"
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.aquarea_tank_temp
        value: >-
          {{ "%.1f" % (trigger.payload | int) }}
  #Sets tank target temperature to the selected value
  - alias: Set tank target temperature
    trigger:
      platform: state
      entity_id: input_number.aquarea_tank_temp
    action:
      service: mqtt.publish
      data_template:
        topic: panasonic_heat_pump/commands/SetDHWTemp
        retain: false #IMPORTANT! ALWAYS set retain flag false for commands!
        payload_template: >-
          {{ "%.0f" % (states('input_number.aquarea_tank_temp') | int) }}
  
  #Fetches cooling offset temperature from status and sets the selector accordingly
  - alias: Set cooling offset temperature selector
    trigger:
      platform: mqtt
      topic: "panasonic_heat_pump/main/Z1_Cool_Request_Temp"
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.aquarea_cool_offset
        value: >-
          {{ "%.1f" % (trigger.payload | int) }}
  #Sets cooling offset temperature to the selected value
  - alias: Set cooling offset temperature
    trigger:
      platform: state
      entity_id: input_number.aquarea_cool_offset
    action:
      service: mqtt.publish
      data_template:
        topic: panasonic_heat_pump/commands/SetZ1CoolRequestTemperature
        retain: false #IMPORTANT! ALWAYS set retain flag false for commands!
        payload_template: >-
          {{ "%.0f" % (states('input_number.aquarea_cool_offset') | int) }}
  
  #Fetches heating delta temperature from status and sets the selector accordingly
  - alias: Set heating delta temperature selector
    trigger:
      platform: mqtt
      topic: "panasonic_heat_pump/main/Heat_Delta"
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.aquarea_heat_delta
        value: >-
          {{ "%.1f" % (trigger.payload | int) }}
  #Sets heating delta temperature to the selected value
  - alias: Set heating delta temperature
    trigger:
      platform: state
      entity_id: input_number.aquarea_heat_delta
    action:
      service: mqtt.publish
      data_template:
        topic: panasonic_heat_pump/commands/SetFloorHeatDelta
        retain: false #IMPORTANT! ALWAYS set retain flag false for commands!
        payload_template: >-
          {{ "%.0f" % (states('input_number.aquarea_heat_delta') | int) }}
  
  #Fetches cooling delta temperature from status and sets the selector accordingly
  - alias: Set cooling delta temperature selector
    trigger:
      platform: mqtt
      topic: "panasonic_heat_pump/main/Cool_Delta"
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.aquarea_cool_delta
        value: >-
          {{ "%.1f" % (trigger.payload | int) }}
  #Sets cooling delta temperature to the selected value
  - alias: Set cooling delta temperature
    trigger:
      platform: state
      entity_id: input_number.aquarea_cool_delta
    action:
      service: mqtt.publish
      data_template:
        topic: panasonic_heat_pump/commands/SetFloorCoolDelta
        retain: false #IMPORTANT! ALWAYS set retain flag false for commands!
        payload_template: >-
          {{ "%.0f" % (states('input_number.aquarea_cool_delta') | int) }}
  
  #Fetches tank delta temperature from status and sets the selector accordingly
  - alias: Set tank delta temperature selector
    trigger:
      platform: mqtt
      topic: "panasonic_heat_pump/main/DHW_Heat_Delta"
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.aquarea_dhw_delta
        value: >-
          {{ "%.1f" % (trigger.payload | int) }}
  #Sets tank delta temperature to the selected value
  - alias: Set tank delta temperature
    trigger:
      platform: state
      entity_id: input_number.aquarea_dhw_delta
    action:
      service: mqtt.publish
      data_template:
        topic: panasonic_heat_pump/commands/SetDHWHeatDelta
        retain: false #IMPORTANT! ALWAYS set retain flag false for commands!
        payload_template: >-
          {{ "%.0f" % (states('input_number.aquarea_dhw_delta') | int) }}

# input_number #
################
input_number:
  aquarea_tank_temp:
    name: Set Tank Temperature
    unit_of_measurement: °C
    mode: box
    min: 40
    max: 75
    step: 1

  aquarea_heat_offset:
    name: Set Heat Request Temperature
    unit_of_measurement: °C
    mode: box
    min: -5
    max: 5
    step: 1

  aquarea_cool_offset:
    name: Set Cool Request Temperature
    unit_of_measurement: °C
    mode: box
    min: -5
    max: 5
    step: 1

  aquarea_heat_delta:
    name: Set Heating Delta
    unit_of_measurement: °C
    mode: box
    min: 0
    max: 10
    step: 1

  aquarea_cool_delta:
    name: Set Cooling Delta
    unit_of_measurement: °C
    mode: box
    min: 0
    max: 10
    step: 1

  aquarea_dhw_delta:
    name: Set DHW Delta
    unit_of_measurement: °C
    mode: box
    min: -10
    max: 0
    step: 1

# input_select #
################
input_select:
  aquarea_quiet_mode:
    name: Set Quiet Mode
    options:
      - "Off"
      - "Level 1"
      - "Level 2"
      - "Level 3"

  aquarea_powerful_mode:
    name: Set Powerful Mode
    options:
      - "Off"
      - "30 min"
      - "60 min"
      - "90 min"

  aquarea_operating_mode:
    name: Set Operating Mode
    options:
      - "Heat"
      - "Cool"
      - "Auto(heat)"
      - "DHW"
      - "Heat+DHW"
      - "Cool+DHW"
      - "Auto(heat)+DHW"

  aquarea_zones:
    name: Set Zones State
    options:
      - "Zone1 active"
      - "Zone2 active"
      - "Zone1 and zone2 active"

# sensor #
##########
sensor:
  #### SENSORS BELOW ARE NOT IN FIRMWARE ####
  #Energy use/production
  - platform: template
    sensors:
      aquarea_energy_production:
        friendly_name: "Aquarea Energy Production"
        unit_of_measurement: "W"
        value_template: >-
          {% if states('sensor.dhw_energy_production') != "0" %}
            {{ states('sensor.dhw_energy_production') }}
          {% elif states('sensor.cool_energy_production') != "0" %}
            {{ states('sensor.cool_energy_production') }}
          {% else %}
            {{ states('sensor.heat_energy_production') }}
          {% endif %}
      aquarea_energy_consumption:
        friendly_name: "Aquarea Energy Consumption"
        unit_of_measurement: "W"
        value_template: >-
          {% if states('sensor.dhw_energy_consumption') != "0" %}
            {{ states('sensor.dhw_energy_consumption') }}
          {% elif states('sensor.cool_energy_consumption') != "0" %}
            {{ states('sensor.cool_energy_consumption') }}
          {% else %}
            {{ states('sensor.heat_energy_consumption') }}
          {% endif %}
  #COP Calculations
  - platform: template
    sensors:
      aquarea_cop:
        friendly_name: "Aquarea COP"
        unit_of_measurement: "x"
        value_template: >-
          {% if states('sensor.aquarea_energy_production') != "Unknown" %}
            {% if states('sensor.aquarea_energy_consumption') > "0" %}
              {{ '%0.1f' % ((states('sensor.aquarea_energy_production') | float ) / (states('sensor.aquarea_energy_consumption') | float)) }}
            {% else %}
              0.0
            {% endif %}
          {% else %}
            unavailable
          {% endif %}

# switch #
##########
switch:
#Turn on/off holiday mode
  - platform: mqtt
    name: SetHolidayMode
    availability_topic: "panasonic_heat_pump/LWT"
    command_topic: "panasonic_heat_pump/commands/SetHolidayMode"
    state_topic: "panasonic_heat_pump/main/Holiday_Mode_State"
    qos: 0
    payload_on: "1"
    payload_off: "0"
    state_on: "On"
    state_off: "Off"
    value_template: >-
      {% if value == "Off" %}
        Off
      {% elif value == "Active" or value == "Scheduled" %}
        On
      {% endif %}
    retain: false
